import re
from typing import List, Tuple, Dict, Any
from rdkit import Chem

ATOM_SYMBOLS = {"c", "n", "o", "f", "p", "s", "cl", "br", "i", "h", "b"}

def align_ligand_tokens(smiles: str, tokens: List[str], mol_with_hs: Chem.Mol = None) -> Tuple[List[int], Dict[str, Any]]:
    """
    Sequentially maps tokenizer tokens back to RDKit atom indices, handling explicit hydrogens.
    
    Args:
        smiles: Canonical SMILES string (typically heavy atoms only).
        tokens: List of tokens generated by the tokenizer.
        mol_with_hs: The original RDKit molecule containing hydrogens.
        
    Returns:
        mapping_indices: List of token indices corresponding to each atom in mol_with_hs.
        stats: Dict of alignment metrics.
    """
    # 1. Align heavy-atom canonical smiles to tokens
    mol_no_hs = Chem.MolFromSmiles(smiles)
    if mol_no_hs is None:
        num_atoms = mol_with_hs.GetNumAtoms() if mol_with_hs is not None else 0
        return [-1] * num_atoms, {"alignment_accuracy": 0.0, "matched_atoms": 0, "unmatched_atoms": 0}
        
    num_heavy = mol_no_hs.GetNumAtoms()
    heavy_mapping = []
    
    matched_count = 0
    unmatched_count = 0
    duplicate_count = 0
    mapped_tokens = set()
    
    token_idx = 0
    for atom_idx in range(num_heavy):
        atom = mol_no_hs.GetAtomWithIdx(atom_idx)
        symbol = atom.GetSymbol().lower()
        
        found = False
        while token_idx < len(tokens):
            tok = tokens[token_idx].lower()
            if symbol in tok and not (tok.startswith("[") or tok.endswith("]")):
                heavy_mapping.append(token_idx)
                if token_idx in mapped_tokens:
                    duplicate_count += 1
                mapped_tokens.add(token_idx)
                token_idx += 1
                matched_count += 1
                found = True
                break
            token_idx += 1
            
        if not found:
            heavy_mapping.append(-1)
            unmatched_count += 1
            
    # 2. Map original atoms (with Hs) to the heavy mapping
    if mol_with_hs is not None:
        mapping_indices = []
        heavy_atom_idx = 0
        for atom in mol_with_hs.GetAtoms():
            if atom.GetAtomicNum() == 1:  # Hydrogen
                mapping_indices.append(-1)
            else:
                if heavy_atom_idx < len(heavy_mapping):
                    mapping_indices.append(heavy_mapping[heavy_atom_idx])
                else:
                    mapping_indices.append(-1)
                heavy_atom_idx += 1
    else:
        mapping_indices = heavy_mapping
        
    total_atoms = mol_with_hs.GetNumAtoms() if mol_with_hs is not None else num_heavy
    accuracy = (matched_count - duplicate_count) / max(1, total_atoms)
    
    stats = {
        "total_atoms": total_atoms,
        "matched_atoms": matched_count,
        "unmatched_atoms": unmatched_count,
        "duplicate_mappings": duplicate_count,
        "mapping_accuracy": accuracy
    }
    
    return mapping_indices, stats


def canonicalize_smiles_safe(raw_smiles: str) -> Tuple[str, Dict[str, Any]]:
    """
    Safely validates and canonicalizes a SMILES string using RDKit (generating heavy-atom smiles).
    """
    diagnostics = {
        "invalid_molecule": False,
        "failed_tokenization": False,
        "average_token_length": 0.0,
        "tokenizer_coverage": 1.0
    }
    
    try:
        mol = Chem.MolFromSmiles(raw_smiles)
        if mol is None:
            diagnostics["invalid_molecule"] = True
            return "", diagnostics
        # Strip Hs for standardized SMILES language model input
        mol_no_hs = Chem.RemoveHs(mol)
        canonical = Chem.MolToSmiles(mol_no_hs, canonical=True)
        return canonical, diagnostics
    except Exception:
        diagnostics["invalid_molecule"] = True
        return "", diagnostics
